DROP TABLE IF EXISTS users;

CREATE TABLE user (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  customerId VARCHAR(250) NOT NULL UNIQUE,
  encryptedRegistrationCode VARCHAR(250) NOT NULL,
  cmkAlias VARCHAR(250) DEFAULT NULL,
  cmkId VARCHAR(250) DEFAULT NULL,
  encryptionKey VARCHAR(250) DEFAULT NULL
);